### ISSUE TITLE
Very nice work. Any paper or code?

### ISSUE THREAD

**Issue by hitdshu** [Shepherddot/Multiple-fisheye-camera-tightly-coupled-inertial-SLAM#1]
Any paper or further code for this repo? Did you participate the hilti challenge and how does the system perform?

**Comment by Shepherddot** [comment]
我已收到，我会尽快查看的

**Comment by Shepherddot** [comment]
Sorry, this is a toy experimental project, there is no reference paper, and i participate the hilti challenge just for fun, i can only know it perform better than multicam-openvins-version. However there is no magic in this code, you may check multicol-slam/openvins these wonderful projects, some thoughts would be inspired.
